---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rmessner-web
  description: The place to be, for great artists
spec:
  type: website
  lifecycle: production
  owner: rmessner-team
  system: rmessner-portal
  dependsOn: ['component:rmessner-service']
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rmessner-service
  description: The place to be, for great artists
spec:
  type: service
  lifecycle: production
  owner: rmessner-team
  system: rmessner-portal
  dependsOn: ['resource:rmessner-db']
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rmessner-db
  description: Stores artist details
spec:
  type: database
  owner: rmessner-team
  system: rmessner-portal
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: rmessner-portal
  description: Handy tools to keep artists in the loop
spec:
  owner: rmessner-team
  domain: rmessner
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: rmessner-team
  description: The infra business unit
spec:
  type: team
  profile:
    displayName: Infrastructure
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: rmessner
spec:
  profile:
    displayName: Jenny Doe
    email: jenny-doe@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [rmessner-team]
